name: Build Alfred Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Build
          run: |
            sudo apt-get -y install zip
          run: |
            zip -r -j ${{ secrets.DIST_FILENAME }} src/*
        - name: Upload Artifact
          uses: actions/upload-artifact@v3
          with:
            name: alfredworkflow
            path: ${{ secrets.DIST_FILENAME }}
