name: Build Alfred Workflow

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened

jobs:
  build:
  runs-on: ubuntu-latest
  steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: vimtor/action-zip@v1
        with:
          files: src/
          recursive: false
          dest: ${{ secrets.DIST_FILENAME }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: alfredworkflow
          path: ${{ secrets.DIST_FILENAME }}
